# Generated by Django 4.2.1 on 2023-07-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
